$schema: "http://json-schema.org/draft-04/schema#"

description: Snakemake configuration file

type: object

properties:

  cellranger_rna_sif:
    description: Singularity image to execute cellranger count (RNA)
    type       : string

  cellranger_multiome_sif:
    description: Singularity image to execute cellranger-arc count (RNA+ATAC)
    type       : string

  cellranger_atac_sif:
    description: Singularity image to execute cellranger-atac count (ATAC)
    type       : string

  genome_reference_gex:
    description: 10X reference genome for cellranger count
    type       : string

  genome_refrerence_arc:
    description: 10X reference genome for cellranger-arc and cellranger-atac count
    type       : string

  cellranger_count:
    type: object
    properties:
      10x_pipeline: { type: string, enum: [ GEX, ATAC, ARC ], description: Type of 10X pipeline. Can be RNA alone (GEX), ATAC alone (ATAC) or multiome -RNA+ATAC- (ARC)}
      introns     : { type: boolean }
      mem         : { type: integer }

  preprocessing:
    type: object
    description: parameters to run Seurat. Minimum cells per gene, species, patterns to select mithocondrial and ribosomal genes (adapt based on species) and markers genes to plot in report
    properties:
      min_cells: { type: integer, minimum: 0, description: "Minimum number of cells that must express a feature."}
      species  : { type: string, enum: [human, mouse], description: Sample species. Can be mouse or human }
      mito_pattern: { type: string, description: Pattern to select mithocondrial genes. ^mt- for mouse, ^MT- for humans }
      ribo_pattern: { type: string, description: Pattern to select ribosomal genes. Rpl|^Rps for mouse, RPL|^RPS for humans }
      marker_genes: { type: array, description: Genes that will be plotted in the final Rmarkdown report. Use a syntax corresponding to your species }
  
  units:
    type: string
    description: path to units.tsv file containing fastq paths and sample names
    
  resources:
    type: string
    description: path to resources.yaml file containing resources used by each rule

  sample_config:
    type: string
    description: path to sample_config.tsv containing cellfiltering parameters for cellranger and Seurat
  
  cell_hashing:
    type: string
    description: path to cell_hashing.yaml containing the mapping of totalseq antibodies to subsample names

  larry_config:
    type: string
    description: path to larry_config.yaml containing the configuration to process LARRY barcodes
