units        : config/samples/units.tsv
sample_config: config/samples/sample_config.tsv
resources    : config/resources.yaml
larry_config : config/larry_config.yaml
cell_hashing : config/cellhash_config.yaml

# Singularity images, reference genome, library and feature-ref (last 2 in case feature barcoding is performed)
cellranger_rna_sif      : /stemcell/data/Singularity_images/cellranger_7.1.0.sif
cellranger_multiome_sif : /stemcell/data/Singularity_images/cellranger_arc_2.0.2.sif
cellranger_atac_sif     : /stemcell/data/Singularity_images/cellranger_atac_2.1.0.sif
genome_reference_gex    : /stemcell/scratch/References/Cellranger/refdata-gex-mm10-2020-A
genome_refrerence_arc   : /stemcell/scratch/References/Cellranger/refdata-cellranger-arc-mm10-2020-A-2.0.0


# Cellranger count parameters
cellranger_count:
  # 10x pipeline: Must be GEX (rnaseq), ATAC or ARC (multiome, RNA + ATAC).
  10x_pipeline : "ARC"
  introns: True
  mem: 120
  extra_parameters_atac: "--nosecondary"
  extra_parameters_rna: "--nosecondary"
  extra_parameters_arc: ""


# Parameters regarding preprocessing of Seurat object
preprocessing:
  # Min number of cells that must express a gene to include it in the final matrix
  min_cells_gene : 5
  # human or mouse
  species: "mouse"
  mito_pattern   : "^mt-"
  ribo_pattern   : "^Rpl|^Rps"
  marker_genes   :
    - Procr
    - Mecom
    - Pf4
    - Elane
    - Flt3
    - Lyz2
    - Akr1c13
    - Ctsg
    - Car1
    - Ms4a2
    - Mki67
    - Plac8
    - Mcpt8
    - Mmp16
    - Ncam2
    - Tgfbr3
    - Tcf15
    - Nupr
    - Rnf220
    - Clu
    - Tppp3