units    : config/units.tsv
resources: config/resources.yaml

cellranger_sif  : /stemcell/data/Singularity_images/cellranger_7.0.0.sif
genome_reference: /stemcell/scratch/References/Cellranger/refdata-gex-mm10-2020-A

cellranger_count:
  introns: True
  n_cells: 8000