units    : config/units.tsv
resources: config/resources.yaml

# Singularity images, reference genome, library and feature-ref (last 2 in case feature barcoding is performed)
cellranger_sif          : /stemcell/data/Singularity_images/cellranger_7.0.0.sif
cellranger_multiome_sif : /stemcell/data/Singularity_images/cellranger_7.0.0.sif
genome_reference_gex    : /stemcell/scratch/References/Cellranger/refdata-gex-mm10-2020-A
genome_refrerence_arc   : /stemcell/scratch/References/Cellranger/refdata-cellranger-arc-mm10-2020-A-2.0.0

# 10x pipeline: Must be GEX (rnaseq), ATAC or ARC (multiome, RNA + ATAC).
10x_pipeline : "GEX"

# Cellranger count parameters
cellranger_count:
  introns: True
  n_cells: 8000
  mem: 120

# feature barcodoing parameters/settings
feature_bc_config:
  # Does the data contain feature barcoding data or not
  feature_bc: True
  # Fastq in which the barcode is located. Can be R1 or R2
  read_feature_bc: "R2"
  # Fastq in which the cellular barcode is located. Must be the opposite of read_feature_bc
  read_cellular_bc: "R1"
  # Hamming distance to collapse barcodes with umicollapse
  hamming_distance: 4 
  # Structure --> barcode-sequence : barcode name. i.e: "ACGT..GTA..GCC..GGGTA..GA" : "Scarlet"
  # Special characters won't be escaped.  
  bc_patterns:
    "TGCTAA....TG....CA....GT....AG...." : "GFP"
    "GTTCCA....TG....CA....GT....AG...." : "Sapphire"
    "AAGATT....TG....CA....GT....AG...." : "Scarlet"