# Maxmem has to be specified in megabytes (To transform gb to mb just do gb*1000)
cellranger_count:
    cpu   : 90
    MaxMem: 128000

collapse_fastq_hd:
    MaxMem: 30000

correct_barcodes:
    MaxMem: 6000

extract_barcodes:
    MaxMem: 16000

create_seurat:
    cpu   : 5
    MaxMem: 100000

RNA_exploration:
    cpu   : 1
    MaxMem: 100000

barcode_exploration:
    cpu   : 1
    MaxMem: 100000